theme: minima
title: Seungryul Ryan Shin
author: srshin@cornell.edu
description: Updated February 2023
# show_excerpts: false
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-include-cache', 'jekyll-gist']
