theme: minima
title: Seungryul Ryan Shin
author: srshin@unist.ac.kr
description: Updated February 2025
# show_excerpts: false
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-include-cache', 'jekyll-gist']
